{% set name = "ngmix" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/ngmix/archive/v{{ version }}.tar.gz
  sha256: e0ddf54ef979f43c290922db4886414db19bf3c5a6edc8c25e255b0583b30828

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - numba <0.41.0a|>=0.43.0  # bug in numba 0.41.* and 0.42.* series
    - scipy
    - galsim
    - emcee

test:
  imports:
    - ngmix

about:
  home: https://github.com/esheldon/ngmix
  license: GPL-2
  license_family: GPL
  license_file: gpl.txt
  summary: 'Gaussian mixtures and image processing implemented in python and C'

extra:
  recipe-maintainers:
    - beckermr
    - esheldon
