travis:
  secure:
    BINSTAR_TOKEN: eKALbOnvhCruvjXjCS4pBGLpR/P+IlEOwjdfJlzpfhUb9XGEj9jfRcVA421we+1vYCx6t45Egk6JBUMHF4Uvm5a4JSInxhgJhHqMeQNBAWkYP7yzeoD2+YUOiuWxCjmGHbt0sxhmBcH/ynFZd+pg7S2u8Xd5Qw7Ij9Twe8RNkReYRwECmSNz5c//YdjdP3Q2XcjYh4OKqL2QDrP2qrfgOlhe/gD6Wu7SuC2xd1grfvXrqtl1e5nZmEFvCAwarrVttjDg2kooMJXosv743+NzokFfAwZQEcRTf3GVJ5isj2q+tRzTJCHiDAdtzTeoAuKv2mB3xirwP1jXQe+Y5xRi0sCkh13r7MbhszmiNnhtZWh2ZLCXuBZc5oa1lIOPDqUnPkWleAjSG2ATg+W+F8hQ+xgw9aRrDeqqwMZRZmkuEH214pZpyWaCXucLZYFQSFNgRLNUOPtOWT/Cwt5mnaWGg9RlsFEi0G1gObBuoPw711dBq7G/TX7sgYcTQI5eOtaYMsEQBXoG16/PiiC43kDK0ulZMHWJ2+Oc9/0UG3qOuZpr/qAXwkznrYnJT8x0qPBwt91XWXt7TNLAXPLs8NuR8wQMZsAfXO0y3PxLC1p3fWHatm4IBATxxKlg4kRzQAhtagys3PuWfrot88yJBj8Qd0sXpkImf2535XWzxr0MQK0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
